F1 = fopen('Paths.txt','wt');
F2 = fopen('Dipoles.txt', 'wt');
   
tic
for j = 1:1
         activity(j, Vertices, VertNormals, F1, F2);
end
toc

function [] = activity(i,Vertices, VertNormals, F1, F2)
        Px = num2str(Vertices(i,1)*1000);
        fprintf(F2,'%s ',Px);
        Py = num2str(Vertices(i,2)*1000);
        fprintf(F2,'%s ',Py);
        Pz = num2str(Vertices(i,3)*1000);
        fprintf(F2,'%s ',Pz);

        Ox = num2str(VertNormals(i,1));
        fprintf(F2,'%s ',Ox);
        Oy = num2str(VertNormals(i,2));
        fprintf(F2,'%s ',Oy);
        Oz = num2str(VertNormals(i,3));
        fprintf(F2,'%s ',Oz);
        fprintf(F2,'%d\n',i);
                        
        def = [Px ',' Py ',' Pz ',' Ox ', ' Oy ',' Oz]; 

         % Input files(Вставь директиву общего сигнала)
        sFiles = {...
            'C:\Users\tener\OneDrive\���������\brainstorm_db\CompMeth\data\1\main\matrix_sim_221125_1854.mat'};

            % Start a new report
            %bst_report('Start', sFiles);



            % Process: Simulate recordings from dipoles
            sFiles = bst_process('CallProcess', 'process_simulate_dipoles', sFiles, [], ...
                'dipoles',  def, ...
                'cs',       'scs', ...  % scs
                'meg',      'os_meg', ...  % Overlapping spheres
                'eeg',      'openmeeg', ...  % OpenMEEG BEM
                'ecog',     '', ...  % 
                'seeg',     '', ...  % 
                'openmeeg', struct(...
                     'BemFiles',     {{}}, ...
                     'BemNames',     {{'Scalp', 'Skull', 'Brain'}}, ...
                     'BemCond',      [1, 0.0125, 1], ...
                     'BemSelect',    [1, 1, 1], ...
                     'isAdjoint',    0, ...
                     'isAdaptative', 1, ...
                     'isSplit',      0, ...
                     'SplitLength',  4000), ...
                'duneuro',  struct(...
                     'FemCond',             [], ...
                     'FemSelect',           [], ...
                     'UseTensor',           0, ...
                     'Isotropic',           1, ...
                     'SrcShrink',           0, ...
                     'SrcForceInGM',        0, ...
                     'FemType',             'fitted', ...
                     'SolverType',          'cg', ...
                     'GeometryAdapted',     0, ...
                     'Tolerance',           1e-08, ...
                     'ElecType',            'normal', ...
                     'MegIntorderadd',      0, ...
                     'MegType',             'physical', ...
                     'SolvSolverType',      'cg', ...
                     'SolvPrecond',         'amg', ...
                     'SolvSmootherType',    'ssor', ...
                     'SolvIntorderadd',     0, ...
                     'DgSmootherType',      'ssor', ...
                     'DgScheme',            'sipg', ...
                     'DgPenalty',           20, ...
                     'DgEdgeNormType',      'houston', ...
                     'DgWeights',           1, ...
                     'DgReduction',         1, ...
                     'SolPostProcess',      1, ...
                     'SolSubstractMean',    0, ...
                     'SolSolverReduction',  1e-10, ...
                     'SrcModel',            'venant', ...
                     'SrcIntorderadd',      0, ...
                     'SrcIntorderadd_lb',   2, ...
                     'SrcNbMoments',        3, ...
                     'SrcRefLen',           20, ...
                     'SrcWeightExp',        1, ...
                     'SrcRelaxFactor',      6, ...
                     'SrcMixedMoments',     1, ...
                     'SrcRestrict',         1, ...
                     'SrcInit',             'closest_vertex', ...
                     'BstSaveTransfer',     0, ...
                     'BstEegTransferFile',  'eeg_transfer.dat', ...
                     'BstMegTransferFile',  'meg_transfer.dat', ...
                     'BstEegLfFile',        'eeg_lf.dat', ...
                     'BstMegLfFile',        'meg_lf.dat', ...
                     'UseIntegrationPoint', 1, ...
                     'EnableCacheMemory',   0, ...
                     'MegPerBlockOfSensor', 0), ...
                'isnoise',  0, ...
                'noise1',   0.1, ...
                'noise2',   0.5, ...
                'savedip',  1, ...
                'savedata', 1);
            
            
            
            % Process: MEAN: [all]
            %sFiles = bst_process('CallProcess', 'process_average_time', sFiles, [], ...
                %'timewindow', [], ...
                %'avg_func',   'mean', ...  % Arithmetic average:  mean(x)
                %'overwrite',  0);
            



            Path = sFiles(1).FileName;
            fprintf(F1,'%s\n',Path);


            % Save and display report
            %ReportFile = bst_report('Save', sFiles);
            %bst_report('Open', ReportFile);
            % bst_report('Export', ReportFile, ExportDir);
end
